### ISSUE TITLE
User Story Join Group Runs

### ISSUE THREAD

**Issue by Sparkeeee** [Sparkeeee/carls-site#3]
As a ** As a keen runner in Dublin** I can **discover how to join others for group runs** so that **my fitness training is a shared experience**

**Comment by Sparkeeee** [comment]
**Tasks**

- [ ] Create calendar area of website.
- [ ] make this editable by admins.
- [ ] Specify who is elligible to join in.
- [ ] give locations and times.
