### ISSUE TITLE
User Story 

### ISSUE THREAD

**Issue by Sparkeeee** [Sparkeeee/carls-site#5]
As a **admin** I can **easily update events** so that **the site is accurate and people can plan ahead**

**Acceptance Criteria**

- Relevant data fields are editable via connection to a CMS.

- The site admins are shown how to use the CMS.

- Site admins have used/tested the CMS and are confident in its use.

**Tasks**

- [ ] Connect CMS to relevant fields of website.
- [ ] Ensure admins are confident in use of CMS.
- [ ] Provide supporting documentation/user guide about CMS use for future reference.
